// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  antBtn: string;
  dispatch: string;
  itemContainer: string;
  prebookingSel: string;
  receiveAdd: string;
  receiveSelect: string;
  receiveTable: string;
  table: string;
  tableBody: string;
}
export const cssExports: CssExports;
export default cssExports;
