// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amap_markers_pop_window': string;
  'btn': string;
  'container': string;
  'containerInfo': string;
  'content': string;
  'distanceSlider': string;
  'iconStyle': string;
  'left': string;
  'left_bottom': string;
  'line': string;
  'markColor': string;
  'prebookBox': string;
  'right': string;
  'searchBox': string;
  'sliderBox': string;
  'sliderInput': string;
  'sliderTitle': string;
  'title': string;
  'trans': string;
}
export const cssExports: CssExports;
export default cssExports;
