export default [
  {
    path: '/user',
    component: '../layouts/UserLayout',
    routes: [
      { path: 'login', component: './Login/Login' }
    ],
  }, {
    path: '/mobile',
    component: '../layouts/MobileLayout',
    routes: [
      // { path: 'formDemo', component: '../mobile/FormMobileDemo/demo' },
      // { path: 'listDemo', component: '../mobile/FormMobileDemo/ListDemo' },
      // { path: 'registry', component: '../mobile/page/registry/Registry', name: '注册', hideInMenu: true },
      { path: 'prebookingList', component: '../mobile/page/prebooking/PrebookingList', name: '预约单列表', hideInMenu: true },
      { path: 'createPrebooking', component: '../mobile/page/prebooking/CreatePrebooking', name: '创建预约单', hideInMenu: true },
      { path: 'createPrebookingByGoodsPlan', component: '../mobile/page/prebooking/CreatePrebookingByGoodsPlan', name: '创建预约单', hideInMenu: true },
      { path: 'prebookingDetail', component: '../mobile/page/prebooking/PrebookingDetail', name: '预约单详情', hideInMenu: true },
      { path: 'createDispatch', component: '../mobile/page/dispatch/CreateDispatch', name: '调度', hideInMenu: true },
      // { path: 'createDispatch2', component: '../mobile/page/dispatch/CreateDispatch2', name: '调度', hideInMenu: true },
      { path: 'transportList', component: '../mobile/page/transport/TransportList', name: '运单列表', hideInMenu: true },
      { path: 'transportDetail', component: '../mobile/page/transport/TransportDetail', name: '运单详情', hideInMenu: true },
      { path: 'transportAudited', component: '../mobile/page/transport/TransportAudited', name: '审核运单', hideInMenu: true },
      { path: 'transportModify', component: '../mobile/page/transport/TransportModify', name: '修改运单', hideInMenu: true },
      { path: 'modifyPassword', component: '../mobile/page/personal/ModifyPassword', name: '修改密码', hideInMenu: true },
      { path: 'aboutUs', component: '../mobile/page/personal/AboutUs', name: '关于我们', hideInMenu: true },
      { path: 'register', component: '../mobile/page/registry/Registry', name: '注册', hideInMenu: true },
      { path: 'registerSuccess', component: '../mobile/page/registry/RegistrySuccess', name: '注册成功', hideInMenu: true },
      { path: 'messageCenter', component: '../mobile/page/personal/MessageCenter', name: '消息中心', hideInMenu: true },
      { path: 'legalNotes', component: '../mobile/page/Protocols/law.jsx', name: '法律说明', hideInMenu: true },
      { path: 'registerNotes', component: '../mobile/page/Protocols/registerNotes.jsx', name: '易键达用户协议', hideInMenu: true },
      { path: 'userAgreement', component: '../mobile/page/Protocols/userAgreement.jsx', name: '易键达用户协议', hideInMenu: true },
      { path: 'privacyProtectionAgreement', component: '../mobile/page/Protocols/privacyProtectionAgreement.jsx', name: '易键达隐私保护协议', hideInMenu: true },
      { path: 'shipmentStatistics', component: '../mobile/page/shipmentStatistics/shipmentStatistics.jsx', name: '托运统计', hideInMenu: true },
      { path: 'forgetPassword', component: '../mobile/page/registry/MissingPassword.jsx', name: '忘记密码', hideInMenu: true },
      // { path: 'demo', component: '../mobile/page/Demo/demo', name: 'demo', hideInMenu: true },
      { path: 'goodsplansDetail', component: '../weapp/pages/goodsplans/CreateGoodsPlans', name: '要货计划单详情', hideInMenu: true},
      { path: 'goodsplansList', component: '../mobile/page/goodsplans/GoodsPlansList', name: '要货计划单列表', hideInMenu: true},
      { path: 'driverPickup', component: '../mobile/page/driverApp/driverPickup', name: '司机提货', hideInMenu: true},
      { path: 'driverSign', component: '../mobile/page/driverApp/driverSign', name: '司机签收', hideInMenu: true},
      { path: 'receivablesAccount', component: '../mobile/page/driverApp/receivablesAccount', name: '收款账号信息', hideInMenu: true},
      { path: 'incomeDetails', component: '../mobile/page/driverApp/incomeDetails', name: '收入明细', hideInMenu: true},
      { path: 'debugger', component: '../mobile/page/driverApp/debugger', name: '获取gps', hideInMenu: true},
      { path: 'contract', component: '../mobile/page/contract', name: '合同详情', hideInMenu: true}
    ]
  }, {
    path: '/Weapp',
    component: '../layouts/WeappLayout',
    routes: [
      {
        path: 'main',
        component: '../layouts/WeappTabBarLayout',
        routes: [
          { path: 'personalCenter', component: '../weapp/pages/personalCenter', name: '个人中心', hideInMenu: true },
          { path: 'messageCenter', component: '../weapp/pages/messageCenter', name: '消息中心', hideInMenu: true },
          { path: 'goodsPlansList', component: '../weapp/pages/goodsplans/GoodsPlansList', name: '计划单&运单列表', hideInMenu: true },
          // { path: 'demo', component: '../weapp/pages/demo/demo.jsx', name: 'demo', hideInMenu: true },
          { path: 'index', component: '../weapp/pages/index/Index', name: '首页', hideInMenu: true },
          { path: 'statistics', component: '../weapp/pages/statistics/Statistics', name: '统计', hideInMenu: true }
        ]
      },
      { path: 'bindContract', component: '../weapp/pages/contract/bindContract', name: '绑定合同', hideInMenu: true },
      { path: 'bindContract/error', component: '../weapp/pages/contract/bindContractError', name: '绑定合同详情', hideInMenu: true },
      { path: 'goodsPlanRelationTransport', component: '../weapp/pages/goodsplans/RelationTransport', name: '关联运单', hideInMenu: true },
      { path: 'createGoodsPlans', component: '../weapp/pages/goodsplans/CreateGoodsPlans', name: '创建要货计划单', hideInMenu: true },
      { path: 'goodsplansDetail', component: '../weapp/pages/goodsplans/CreateGoodsPlans', name: '要货计划单详情', hideInMenu: true},
      // { path: 'transportlist', component: '../weapp/pages/transport/TransportList', name: '运单列表', hideInMenu: true},
      { path: 'transportDetail', component: '../weapp/pages/transport/TransportDetail', name: '运单详情', hideInMenu: true },
      { path: 'transportDetail/trackMap', component: '../weapp/pages/transport/TrackMap/TrackMap', name: '地图轨迹', hideInMenu: true },
      { path: 'receivingList', component: '../weapp/pages/receiving/ReceivingList', name: '卸货点列表', hideInMenu: true },
      { path: 'addreceiving', component: '../weapp/pages/receiving/AddReceiving', name: '新建卸货点', hideInMenu: true },
      { path: 'modifyreceiving', component: '../weapp/pages/receiving/AddReceiving', name: '修改卸货点', hideInMenu: true },
      { path: 'receivingDetail', component: '../weapp/pages/receiving/AddReceiving', name: '卸货点详情', hideInMenu: true },
      { path: 'personalCenter/contractList', component: '../weapp/pages/personalCenter/centerPage/ContractList', name: '合同列表', hideInMenu: true },
      { path: 'personalCenter/SubAccountList', component: '../weapp/pages/personalCenter/centerPage/SubAccountList', name: '子账号列表', hideInMenu: true },
      { path: 'personalCenter/contractList/contractDetail', component: '../weapp/pages/personalCenter/centerPage/ContractDetail', name: '合同详情', hideInMenu: true },
      { path: 'personalCenter/modifypassword', component: '../weapp/pages/personalCenter/centerPage/ModifyPassword' ,name: '修改密码', hideInMenu: true },
      // { path: 'personalCenter/contractList/contractDetail/customerAddInfo', component: '../weapp/pages/personalCenter/centerPage/AddContractInfo' ,name: '选择卸货点', hideInMenu: true },
      { path: 'personalCenter/stastisitics', component: '../weapp/pages/statistics/Statistics', name: '统计', hideInMenu: true},
      { path: 'todoList', component: '../weapp/pages/todolist/TodoList', name: '待办列表', hideInMenu: true }
    ]
  }, {
    path: '/WeappDriver',
    component: '../layouts/WeappDriverLayout',
    routes: [
      {
        path: 'main',
        component: '../layouts/WeappDriverTabBarLayout',
        routes: [
          { path: 'personalCenter', component: '../weappDriver/pages/personalCenter', name: '个人中心', hideInMenu: true },
          { path: 'hall', component: '../weappDriver/pages/orderHall', name: '接单大厅', hideInMenu: true },
          // { path: 'goodsPlansList', component: '../weappDriver/pages/goodsplans/GoodsPlansList', name: '计划单&运单列表', hideInMenu: true },
          // // { path: 'demo', component: '../weapp/pages/demo/demo.jsx', name: 'demo', hideInMenu: true },
          { path: 'index', component: '../weappDriver/pages/Index', name: '首页', hideInMenu: true },
          { path: 'index/transportDetail', component: '../weappDriver/pages/Index/transportDetail', name: '运单详情', hideInMenu: true },
          // { path: 'statistics', component: '../weappDriver/pages/statistics/Statistics', name: '统计', hideInMenu: true }
        ]
      },
      { path: 'joinUs', component: '../weappDriver/pages/login/JoinUs', name: '加入我们', hideInMenu: true },
      { path: 'login', component: '../weappDriver/pages/login', name: '登录', hideInMenu: true },
      { path: 'login/registry', component: '../weappDriver/pages/registry', name: '注册', hideInMenu: true },
      { path: 'login/registrySetting', component: '../weappDriver/pages/setPassword/registrySetting', name: '设置密码', hideInMenu: true },
      { path: 'login/forgetPassword', component: '../weappDriver/pages/forgetPassword', name: '忘记密码', hideInMenu: true },
      { path: 'login/setPassword', component: '../weappDriver/pages/setPassword', name: '设置密码', hideInMenu: true },
      { path: 'setting', component: '../weappDriver/pages/setting', name: '设置', hideInMenu: true },
      { path: 'setting/accountSafe', component: '../weappDriver/pages/setting/AccountSafe', name: '账户安全', hideInMenu: true },
      { path: 'setting/accountSafe/modifyPhone', component: '../weappDriver/pages/setting/components/CheckPhone', name: '更改手机号', hideInMenu: true },
      { path: 'setting/accountSafe/newPhone', component: '../weappDriver/pages/setting/components/NewPhone', name: '更改手机号', hideInMenu: true },
      { path: 'setting/accountSafe/modifyPassword', component: '../weappDriver/pages/setting/components/CheckPhone', name: '修改密码', hideInMenu: true },
      { path: 'setting/accountSafe/newPassword', component: '../weappDriver/pages/setting/components/NewPassword', name: '修改密码', hideInMenu: true },
      { path: 'feedback', component: '../weappDriver/pages/feedback', name: '意见反馈', hideInMenu: true },
      { path: 'feedback/transportException', component: '../weappDriver/pages/feedback/transportException', name: '运单异常', hideInMenu: true },
      { path: 'feedback/detail', component: '../weappDriver/pages/feedback/subPages/recordDetail', name: '意见反馈', hideInMenu: true },
      { path: 'income', component: '../weappDriver/pages/income/Income', name: '收益', hideInMenu: true },
      { path: 'income/withdrawalQualification', component: '../weappDriver/pages/income/subPages/WithdrawalQualification', name: '提现资格认证', hideInMenu: true },
      { path: 'income/WithdrawalRecords', component: '../weappDriver/pages/income/subPages/WithdrawalRecords', name: '提现记录', hideInMenu: true },
      { path: 'income/WithdrawalRecords/detail', component: '../weappDriver/pages/income/subPages/Detail', name: '提现详情', hideInMenu: true },
      { path: 'setting/legalNotes', component: '../mobile/page/Protocols/law', name: '法律条款', hideInMenu: true },
      { path: 'setting/registerNotes', component: '../mobile/page/Protocols/registerNotes', name: '易键达用户协议', hideInMenu: true },
      { path: 'carIntelligence', component: '../weappDriver/pages/carIntelligence', name: '车辆', hideInMenu: true },
      { path: 'carComplete', component: '../weappDriver/pages/carIntelligence/carComplete', name: '车辆完善', hideInMenu: true },
      { path: 'carSetting', component: '../weappDriver/pages/carIntelligence/carSetting', name: '车辆管理', hideInMenu: true },
      { path: 'findCar', component: '../weappDriver/pages/carIntelligence/findCar', name: '车辆检索', hideInMenu: true },
      { path: 'findList', component: '../weappDriver/pages/carIntelligence/findList', name: '车辆检索结果', hideInMenu: true },
      { path: 'carCongratulation', component: '../weappDriver/pages/carIntelligence/carCongratulation', name: '车辆注册', hideInMenu: true },
      // { path: 'auditInfo', component: '../weappDriver/pages/carIntelligence/auditInfo', name: '车辆', hideInMenu: true },
      { path: 'carCertification', component: '../weappDriver/pages/carIntelligence/carCertification', name: '车辆', hideInMenu: true },
      { path: 'intelligence', component: '../weappDriver/pages/intelligence/Intelligence', name: '资质', hideInMenu: true },
      { path: 'userCheck', component: '../weappDriver/pages/intelligence/component/UserCheck', name: '资质', hideInMenu: true },
      { path: 'congratulation', component: '../weappDriver/pages/intelligence/component/Congratulation', name: '实名认证', hideInMenu: true },
      { path: 'certification', component: '../weappDriver/pages/intelligence/Certification', name: '资质', hideInMenu: true },
      { path: 'unComplete', component: '../weappDriver/pages/intelligence/component/UnComplete', name: '完善资料', hideInMenu: true },
      { path: 'complete', component: '../weappDriver/pages/intelligence/component/Complete', name: '资质', hideInMenu: true },
      { path: 'licenseValidityEdit', component: '../weappDriver/pages/intelligence/component/LicenseValidityEdit', name: '资质', hideInMenu: true },
      { path: 'qualificationValidityEdit', component: '../weappDriver/pages/intelligence/component/QualificationValidityEdit', name: '资质', hideInMenu: true },
      { path: 'history', component: '../weappDriver/pages/transports/History', name: '运单历史', hideInMenu: true },
      { path: 'driverPickup', component: '../weappDriver/pages/transports/driverPickUp', name: '请完成提货', hideInMenu: true },
      { path: 'driverReceive', component: '../weappDriver/pages/transports/driverReceive', name: '请完成到站', hideInMenu: true },
      { path: 'deliveryMap', component: '../weappDriver/pages/transports/deliveryMap', name: '确认提货点', hideInMenu: true },
      { path: 'driverSign', component: '../weappDriver/pages/transports/driverSign', name: '请完成签收', hideInMenu: true },
      { path: 'driverResign', component: '../weappDriver/pages/transports/driverResign', name: '重新签收', hideInMenu: true },
      { path: 'transportsDetail', component: '../weappDriver/pages/transports/component/DetailPage', name: '运单详情', hideInMenu: true },
      { path: 'bankCard', component: '../weappDriver/pages/bankCard/index', name: '银行卡', hideInMenu: true },
      { path: 'customerService', component: '../weappDriver/pages/customerService/index', name: '在线客服', hideInMenu: true },
      { path: 'addBankCard', component: '../weappDriver/pages/bankCard/components/Add', name: '添加银行卡', hideInMenu: true },
      { path: 'bankManager', component: '../weappDriver/pages/bankCard/BankManager', name: '银行卡管理', hideInMenu: true },
      { path: 'hallList', component: '../weappDriver/pages/orderHall/ListIndex', name: '预约单列表', hideInMenu: true },
      { path: 'prebookingDetail', component: '../weappDriver/pages/orderHall/Detail', name: '预约单详情', hideInMenu: true },
      { path: 'collectionCode', component: '../weappDriver/pages/collectionCode', name: '我的收款码', hideInMenu: true },
      {path : 'instrument' , component: '../weappDriver/pages/instrumentRent/List' , name : '租赁页面' , hideInMenu:  true},
      {path : 'instrumentDetail' , component: '../weappDriver/pages/instrumentRent/Detail' , name : '我租赁的设备' , hideInMenu:  true},
      {path : 'instrumentRent' , component: '../weappDriver/pages/instrumentRent/Rent', name :'我要租赁' , hideInMenu: true}
      // { path: 'Demo', component: '../weappDriver/pages/orderHall/component/Demo', name: '城市选择', hideInMenu: true },
      // { path: 'Demo2', component: '../weappDriver/pages/orderHall/component/Demo2', name: '城市选择', hideInMenu: true }
    ]
  }, {
    path: '/WeappConsign',
    component: '../layouts/WeappConsignLayout',
    routes: [
      {
        path: 'main',
        component: '../layouts/WeappConsignTabBarLayout',
        routes: [
          { path: 'dataStatistics', component: '../weappConsign/pages/dataStatistics', name: '首页', hideInMenu: true },
          { path: 'personalCenter', component: '../weappConsign/pages/personalCenter', name: '我的', hideInMenu: true },
          { path: 'release', component: '../weappConsign/pages/releasePrebooking', name: '发布预约单', hideInMenu: true },
          { path: 'staging', component: '../weappConsign/pages/workbench', name: '工作台', hideInMenu: true },
          { path: 'staging/transportDetail', component: '../weappConsign/pages/workbench/transportDetail', name: '运单详情', hideInMenu: true },
          { path: 'prebookingDetail', component: '../weappConsign/pages/workbench/component/PrebookingDetail', name: '预约单详情', hideInMenu: true },
        ]
      },
      { path: 'prebookingQRCode', component: '../weappConsign/pages/releasePrebooking/components/PrebookingQRCode', name: '发布成功', hideInMenu: true },
      { path: 'login', component: '../weappConsign/pages/login', name: '登录', hideInMenu: true },
      { path: 'login/forgetPassword', component: '../weappConsign/pages/forgetPassword', name: '忘记密码', hideInMenu: true },
      { path: 'customerService', component: '../weappConsign/pages/customerService/index', name: '在线客服', hideInMenu: true },
      { path: 'login/setPassword', component: '../weappConsign/pages/setPassword', name: '设置密码', hideInMenu: true },
      { path: 'editPrebooking', component: '../weappConsign/pages/workbench/component/EditPrebooking', name: '修改预约单', hideInMenu: true },
      { path: 'setting', component: '../weappConsign/pages/setting', name: '设置', hideInMenu: true },
      { path: 'setting/legalNotes', component: '../mobile/page/Protocols/law', name: '法律条款', hideInMenu: true },
      { path: 'setting/registerNotes', component: '../mobile/page/Protocols/registerNotes', name: '易键达用户协议', hideInMenu: true },
      { path: 'accountBill', component: '../weappConsign/pages/accountBill/Index', name: '对账单', hideInMenu: true },
      { path: 'accountBill/detail', component: '../weappConsign/pages/accountBill/components/Detail', name: '对账单详情', hideInMenu: true },
      { path: 'paymentBill', component: '../weappConsign/pages/paymentBill/Index', name: '付款单', hideInMenu: true },
      { path: 'paymentBill/detail', component: '../weappConsign/pages/paymentBill/components/Detail', name: '付款单详情', hideInMenu: true },
      { path: 'dataOverview', component: '../weappConsign/pages/dataOverview', name: '数据总览', hideInMenu: true },
      { path: 'reservation', component: '../weappConsign/pages/reservation', name: '预约单', hideInMenu: true },
      { path: 'reservation/detail', component: '../weappConsign/pages/reservation/component/reservationDetail', name: '预约单详情', hideInMenu: true },
      { path: 'reservation/judge', component: '../weappConsign/pages/reservation/judge', name: '提货审核', hideInMenu: true },
      { path: 'reservation/payment', component: '../weappConsign/pages/reservation/payment', name: '支付', hideInMenu: true },
      { path: 'followProject', component: '../weappConsign/pages/dataStatistics/followProject', name: '添加/取消关注的项目', hideInMenu: true },
      { path: 'dataStatistics/detail', component: '../weappConsign/pages/dataStatistics/details', name: '单个项目数据分析', hideInMenu: true },
    ]
  }, {
    path: '/',
    redirect: '/mobile/prebookingList'
  }
]
