// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  content: string;
  header: string;
  logo: string;
  pagination: string;
  prebookItem: string;
  prebookList: string;
  prebookNo: string;
  prebookTitle: string;
  projectLabel: string;
  projectSelector: string;
  selectorDropdown: string;
}
export const cssExports: CssExports;
export default cssExports;
