import auth from "./authCodes";

const {
  USER_SETTING_FORBID,
  USER_SETTING_ENABLE,
  USER,
  FUNDS_INSIDETRANSFER_CHANGE_PHONE,
  DEVICE_RENT_MANAGE_AUDIT,
  DEVICE_RENT_MANAGE_RETURN,
  DEVICE_RENT_MANAGE_RETURN_DEPOSIT,
  GPS_DEVICE_MANAGE_MODIFY,
  GPS_DEVICE_MANAGE_CREATE,
  GPS_ACCOUNT_MANAGE_ENABLE,
  GPS_ACCOUNT_MANAGE_DISABLE,
  SUPPLIER_MANAGE_DISABLE,
  SUPPLIER_MANAGE_ENABLE,
  DEVICE_RENT_MANAGE_MODIFY,
  DEVICE_RENT_MANAGE_CREATE,

  // 托运审核平台对账
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_VISIT,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_EXCEL,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_TRANSPORT,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_EXECUTE,

  // 平台对托运发起对账
  PLAT_TO_CONSIGNMENT_ACCOUNT,
  PLAT_TO_CONSIGNMENT_ACCOUNT_VISIT,
  PLAT_TO_CONSIGNMENT_ACCOUNT_CREATE,
  PLAT_TO_CONSIGNMENT_ACCOUNT_MODIFY,
  PLAT_TO_CONSIGNMENT_ACCOUNT_CANCEL,
  PLAT_TO_CONSIGNMENT_ACCOUNT_BILL,
  PLAT_TO_CONSIGNMENT_ACCOUNT_PDF,
  PLAT_TO_CONSIGNMENT_ACCOUNT_EXCEL,
  PLAT_TO_CONSIGNMENT_ACCOUNT_TRANSPORT,

  // 平台对承运发起对账
  PLAT_TO_SHIPMENT_ACCOUNT,
  PLAT_TO_SHIPMENT_ACCOUNT_VISIT,
  PLAT_TO_SHIPMENT_ACCOUNT_CREATE,
  PLAT_TO_SHIPMENT_ACCOUNT_MODIFY,
  PLAT_TO_SHIPMENT_ACCOUNT_CANCEL,
  PLAT_TO_SHIPMENT_ACCOUNT_BILL,
  PLAT_TO_SHIPMENT_ACCOUNT_PDF,
  PLAT_TO_SHIPMENT_ACCOUNT_EXCEL,
  PLAT_TO_SHIPMENT_ACCOUNT_TRANSPORT,


} = auth;

const useLessAuth = [
  USER_SETTING_FORBID,
  USER_SETTING_ENABLE,
  USER,
  FUNDS_INSIDETRANSFER_CHANGE_PHONE,
  DEVICE_RENT_MANAGE_AUDIT,
  DEVICE_RENT_MANAGE_RETURN,
  DEVICE_RENT_MANAGE_RETURN_DEPOSIT,
  GPS_DEVICE_MANAGE_MODIFY,
  GPS_DEVICE_MANAGE_CREATE,
  SUPPLIER_MANAGE_ENABLE,
  SUPPLIER_MANAGE_DISABLE,
  GPS_ACCOUNT_MANAGE_ENABLE,
  GPS_ACCOUNT_MANAGE_DISABLE,
  DEVICE_RENT_MANAGE_MODIFY,
  DEVICE_RENT_MANAGE_CREATE,

  CONSIGNMENT_AUDIT_PLAT_ACCOUNT,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_VISIT,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_EXCEL,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_TRANSPORT,
  CONSIGNMENT_AUDIT_PLAT_ACCOUNT_EXECUTE,

  PLAT_TO_CONSIGNMENT_ACCOUNT,
  PLAT_TO_CONSIGNMENT_ACCOUNT_VISIT,
  PLAT_TO_CONSIGNMENT_ACCOUNT_CREATE,
  PLAT_TO_CONSIGNMENT_ACCOUNT_MODIFY,
  PLAT_TO_CONSIGNMENT_ACCOUNT_CANCEL,
  PLAT_TO_CONSIGNMENT_ACCOUNT_BILL,
  PLAT_TO_CONSIGNMENT_ACCOUNT_PDF,
  PLAT_TO_CONSIGNMENT_ACCOUNT_EXCEL,
  PLAT_TO_CONSIGNMENT_ACCOUNT_TRANSPORT,

  PLAT_TO_SHIPMENT_ACCOUNT,
  PLAT_TO_SHIPMENT_ACCOUNT_VISIT,
  PLAT_TO_SHIPMENT_ACCOUNT_CREATE,
  PLAT_TO_SHIPMENT_ACCOUNT_MODIFY,
  PLAT_TO_SHIPMENT_ACCOUNT_CANCEL,
  PLAT_TO_SHIPMENT_ACCOUNT_BILL,
  PLAT_TO_SHIPMENT_ACCOUNT_PDF,
  PLAT_TO_SHIPMENT_ACCOUNT_EXCEL,
  PLAT_TO_SHIPMENT_ACCOUNT_TRANSPORT,
];

export default useLessAuth;
