// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'active_icon': string;
  'bottom': string;
  'bottom_icon': string;
  'carContainer': string;
  'centerSelect': string;
  'container': string;
  'fenbutu': string;
  'floatRight': string;
  'header': string;
  'messagePopover': string;
  'searchCar': string;
  'text': string;
  'time': string;
  'timeDes': string;
  'tipsIcon': string;
  'titleChart': string;
}
export const cssExports: CssExports;
export default cssExports;
