// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'fullHeader': string;
  'fullPreBooking': string;
  'fullRight': string;
  'header': string;
  'layout': string;
  'preBooking': string;
  'right': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
