const TRANSPORTIMMEDIATESTATUS = {
  UNTREATED: 1,
  ACCEPT: 2,
  CANCEL: 3,
  COMPLETE: 4,
  UNDELIVERY: 5,
  RECEIVED: 6,
  TRANSPORTING: 7,
  SHIPMENT_REFUSE: 8,
  SHIPMENT_AUDITED: 9,
  CONSIGNMENT_REFUSE: 10,
  SIGNED: 11,
  RESINGED: 12,
  DRIVER_REFUSE: 13,
  TRANSPORT_EXECPTION: 14,
  CUSTOMER_UNAUDITED:15,
  CONSIGNMENT_UNAUDITED:16,
  UNJUDGE:17,
  JUDGE_REFUCE:18,
  CANCEL_APPLY:19,
  TRANSPORT_TIMEOUT:20,
  DELIVERY_UNAUDITED:21,
  DELIVERY_AUDITED_REFUSE:22
}

export const TRANSPORT_FINAL_STATUS = {
  UNTREATED: 0, // 未接单
  ACCEPT: 1, // 已接单
  DRIVER_REFUSE: 2, // 司机拒绝
  CANCEL: 3, // 已取消
  CONSIGNMENT_REFUSE: 4, // 托运拒绝
  COMPLETE: 5, // 已完成
  SHIPMENT_REFUSE: 6, // 客户已拒绝
  UNDELIVERY: 7, // 待提货
  TRANSPORTING: 8, // 运输中
  RECEIVED: 9, // 已到站
  SIGNED: 10, // 已签收
  TRANSPORT_EXECPTION: 11, // 运单异常
  SHIPMENT_UNAUDITED:13, // 客户待审核
  ACCEPT_UNTREATED: 14, // 接单待确认
  DELIVERY_UNTREATED: 15, // 提货待审核
  DELIVERY_REFUSE: 16, // 提货已拒绝
}

export default TRANSPORTIMMEDIATESTATUS
