const UNTREATED = 1
const ACCEPT = 2
const CANCEL = 3
const COMPLETE = 4
const UNDELIVERY = 5
const RECEIVED = 6
const TRANSPORTING = 7
const CUSTOMER_REFUSE = 8
const CUSTOMER_AUDITED = 9
const CONSIGNMENT_REFUSE = 10
const SIGNED = 11
const RESINGED = 12
const REFUSED = 13
const TRANSPORT_EXECPTION = 14
const CUSTOMER_UNAUDITED = 15
const CONSIGNMENT_UNAUDITED = 16
const UNJUDGE = 17
const JUDGE_REFUCE = 18
const CANCEL_APPLY = 19
const TRANSPORT_TIMEOUT = 20
const DELIVERY_UNAUDITED = 21
const DELIVERY_AUDITED_REFUSE = 22

export const TRANSPORTIMMEDIATESTATUS = {
  UNTREATED,
  ACCEPT,
  CANCEL,
  COMPLETE,
  UNDELIVERY,
  RECEIVED,
  TRANSPORTING,
  CUSTOMER_REFUSE,
  CUSTOMER_AUDITED,
  CONSIGNMENT_REFUSE,
  SIGNED,
  RESINGED,
  REFUSED,
  TRANSPORT_EXECPTION,
  CUSTOMER_UNAUDITED,
  CONSIGNMENT_UNAUDITED,
  UNJUDGE,
  JUDGE_REFUCE,
  CANCEL_APPLY,
  TRANSPORT_TIMEOUT,
  DELIVERY_UNAUDITED,
  DELIVERY_AUDITED_REFUSE
}
export const transportImmediateStatusConfig = {
  [UNTREATED]: '未接单',
  [ACCEPT]: '已接单',
  [CANCEL]: '已取消',
  [COMPLETE]: '已完成',
  [UNDELIVERY]: '待提货',
  [RECEIVED]: '已到站',
  [TRANSPORTING]: '运输中',
  [CUSTOMER_REFUSE]: '客户已拒绝',
  [CUSTOMER_AUDITED]: '客户已审核',
  [CONSIGNMENT_REFUSE]: '托运已拒绝',
  [SIGNED]: '已签收',
  [RESINGED]: '重新签收',
  [REFUSED]: '司机拒绝',
  [TRANSPORT_EXECPTION]: '运单异常',
  [CUSTOMER_UNAUDITED]: '客户待审',
  [CONSIGNMENT_UNAUDITED]: '托运待审',
  [UNJUDGE]:'待确定',
  [JUDGE_REFUCE]:'审核不通过',
  [CANCEL_APPLY]:'司机取消申请',
  [TRANSPORT_TIMEOUT]:'运单超时自动关闭',
  [DELIVERY_UNAUDITED]:'提货待审核',
  [DELIVERY_AUDITED_REFUSE]:'提货审核不通过'
}

// 已调度
export const SCHEDULEDSTATUS = [ UNTREATED, ACCEPT, COMPLETE, UNDELIVERY, RECEIVED, TRANSPORTING, CUSTOMER_REFUSE, CUSTOMER_AUDITED,
  CUSTOMER_AUDITED, CONSIGNMENT_REFUSE, SIGNED, RESINGED, TRANSPORT_EXECPTION ]

// 运输中状态
export const INTRANSPORTATIONSTATUS = [ UNDELIVERY, RECEIVED, TRANSPORTING ]

// 确认收货状态
export const COMPLETESTATUS = [COMPLETE, SIGNED, CUSTOMER_REFUSE, CUSTOMER_AUDITED, CONSIGNMENT_REFUSE ]

// 运单异常

export const EXECPTIONSTATUS = [TRANSPORT_EXECPTION]
